syntax on
set background=dark
colorscheme hybrid

" indent files based on filetype
filetype plugin indent on

" make backspace behave normally
set backspace=2
" display line numbers
set number
" number of columns in a tab
set tabstop=4
" number of columns to shift tabs using << and >> operators
set shiftwidth=4
" convert tabs to spaces
set expandtab

" Ignore letter case when searching
set ignorecase
" If the search pattern is lowercase, ignore case
set smartcase

set incsearch
set nohlsearch

set nowrap

set splitbelow
set splitright

" set the working dir to that of the currently open buffer
set autochdir

" preserve undo history
set hidden

" Load file changes without prompting
set autoread

" wrap lines
set wrap
set linebreak
set showbreak=+

" store swap and backup files elsewhere (not with the project files)
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//

" Allow resizing vim splits with a mouse in tmux
set mouse+=a
if &term =~ '^screen'
    set ttymouse=xterm2
endif

" set up delimitMate to autoindent after braces
let delimitMate_expand_cr=1

" Various shortcuts
let mapleader = ","
nnoremap <Leader>w :w<CR>
nnoremap <Leader>q :q<CR>
nnoremap <Leader>a :wq<CR>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
nnoremap <Leader>[ :bprevious<CR>
nnoremap <Leader>] :bnext<CR>
nnoremap <Leader>l :bdelete<CR>
nnoremap <Leader>s :SyntasticToggleMode<CR>

" override php syntax highlighting
function! PhpSyntaxOverride()
    hi! def link phpDocTags  phpDefine
    hi! def link phpDocParam phpType
endfunction

augroup phpSyntaxOverride
    autocmd!
    autocmd FileType php call PhpSyntaxOverride()
augroup END

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-n>"
let g:UltiSnipsJumpBackwardTrigger="<c-b>"

" Syntastic configuration
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

" set syntax highlighting for specific filetypes
au BufNewFile,BufRead *.less set filetype=less
au BufRead,BufNewFile *.asm set filetype=nasm
