# Source the exports
source ~/.exports

# Source the aliases
source ~/.aliases

# Source various utilities
source ~/.utilities

# Source local zsh configurations
if [ -f ~/.zsh_local ]; then
    source ~/.zsh_local
fi
